global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "next-app"
    metrics_path: /api/metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: "0"
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0
    static_configs:
      - targets:
          - "host.docker.internal:3000"

  # PostgreSQL exporter
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9630"]